### ISSUE TITLE
Setting property Error

### ISSUE THREAD

**Issue by itphixl** [chill117/express-mysql-session#41]
Hi ! 
I've a weird error : 

```
10% 0/1 build modules/Users/aurelienphixl/Documents/PhiXL Work/MyNetwork/node_modules/express-session-mysql/lib/index.js:39
this.options = options || {};

TypeError: Cannot set property 'options' of undefined
at module.exports (/Users/aurelienphixl/Documents/PhiXL Work/MyNetwork/node_modules/express-session-mysql/lib/index.js:39:15)
at Object.<anonymous> (/Users/aurelienphixl/Documents/PhiXL Work/MyNetwork/app.js:9:63)
at Module._compile (module.js:541:32)
at Object.Module._extensions..js (module.js:550:10)
at Module.load (module.js:456:32)
at tryModuleLoad (module.js:415:12)
at Function.Module._load (module.js:407:3)
at Module.require (module.js:466:17)
at require (internal/module.js:20:19)
at Object.<anonymous> (/Users/aurelienphixl/Documents/PhiXL Work/MyNetwork/bin/www:7:11)    
```                     

I'm using Node 6.0.0, Express 4.13.1, Express-session 1.13.0
I'm not really sure to understand it.

Can you help me ? :) 

Thanks

**Comment by chill117** [comment]
I believe you are missing the `new` keyword when creating your session store. Should look like this:
```js
var options = {
    // Your options for express-mysql-session go here...
};
var sessionStore = new MySQLStore(options);
```

**Comment by itphixl** [comment]
Unfortunately no :(

This error appears when I make the require statement : 

```
var session                 = require('express-session');
var store                     = require('express-session-mysql')(session);
```

If I comment the second line of the code above, the error doesn't exist anymore.

**Comment by chill117** [comment]
Are you using the old version of this module? Version 0.x of this module is not compatible with the latest documentation, because the constructor was changed.

**Comment by itphixl** [comment]
Oh okay I see. 
My bad, I made a huge mistake. I've installed 'express-session-mysql' and not your module who is 'express-mysql-session'. 

This work perfectly now.

I'm very sorry for to have bothered you. 
I close the issue. 

Thank you very much for your time.
