### ISSUE TITLE
Unexpected token u in JSON at position 0

### ISSUE THREAD

**Issue by MM4005** [chill117/express-mysql-session#58]
Upon trying to create the MySqlStore variable I get this error.
```
undefined:1
undefined
^

SyntaxError: Unexpected token u in JSON at position 0
    at Object.parse (native)
    at MySQLStore.clone (C:\Projects\wclb\node_modules\express-mysql-session\lib\index.js:403:15)
    at new MySQLStore (C:\Projects\wclb\node_modules\express-mysql-session\lib\index.js:40:23)
    at module.exports (C:\Projects\wclb\node_modules\express-mysql-session\lib\index.js:427:10)
    at Object.<anonymous> (C:\Projects\wclb\app.js:8:50)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

This is my code up to where the error occurs
```
var express = require('express');
var app = express();
var session = require('cookie-session');
var MySQLStore = require('express-mysql-session')(session);
```
I am using node v6.9.5 and expressjs v4.14.1 and express-mysql-session v1.2.0.

**Comment by chill117** [comment]
Looks like the cookie-session module is likely the problem. I'll try to test it myself in the next day.

**Comment by MM4005** [comment]
The error occurs at the line `var MySQLStore = require('express-mysql-session')(session)`. I do have that later in my code, but never reach it due to the error.

**Comment by chill117** [comment]
What version of this module are you using? I suspect you're using the old version (`0.x`). The constructor changed for version `1.x`.

**Comment by MM4005** [comment]
am using node v6.9.5 and expressjs v4.14.1 and express-mysql-session v1.2.0.

**Comment by MM4005** [comment]
I have tested this on my personal computer (windows 10) and my vps (debian 8), with the states versions above, and have the issue on both systems.

**Comment by MM4005** [comment]
Cant believe I messed it up. I did `var session = require('cookie-session');` when i should have been doing `var session = require('express-session');`

**Comment by chill117** [comment]
So cookie-session was the problem after all? I'll have to look into why.
