### ISSUE TITLE
Session.reload() and Session.regenerate() crashes

### ISSUE THREAD

**Issue by sirhypernova** [chill117/express-mysql-session#74]
When I use `Session.reload()`:
```
express-mysql-session:log Getting session: -gtR1_DES5uOo0ynN2HBR1BsyKHrH-ZH +8s
node_modules/mysql/lib/protocol/Parser.js:80
        throw err; // Rethrow non-MySQL errors
        ^

TypeError: Cannot read property 'apply' of undefined
    at /home/ubuntu/workspace/now/node_modules/express-session/index.js:374:19
    at /home/ubuntu/workspace/now/node_modules/express-session/session/session.js:93:23
    at Query._callback (/home/ubuntu/workspace/now/node_modules/express-mysql-session/lib/index.js:145:4)
    at Query.Sequence.end (/home/ubuntu/workspace/now/node_modules/mysql/lib/protocol/sequences/Sequence.js:88:24)
    at Query._handleFinalResultPacket (/home/ubuntu/workspace/now/node_modules/mysql/lib/protocol/sequences/Query.js:139:8)
    at Query.EofPacket (/home/ubuntu/workspace/now/node_modules/mysql/lib/protocol/sequences/Query.js:123:8)
    at Protocol._parsePacket (/home/ubuntu/workspace/now/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/home/ubuntu/workspace/now/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/home/ubuntu/workspace/now/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/home/ubuntu/workspace/now/node_modules/mysql/lib/Connection.js:103:28)
```

When I use `Session.regenerate()`:
```
express-mysql-session:log Destroying session: JakI68DtGl46MZVIuW2oZcCavRarYa1l +40s

/home/ubuntu/workspace/now/node_modules/mysql/lib/protocol/Parser.js:80
        throw err; // Rethrow non-MySQL errors
        ^

TypeError: fn is not a function
    at /home/ubuntu/workspace/now/node_modules/express-session/session/store.js:54:5
    at Query._callback (/home/ubuntu/workspace/now/node_modules/express-mysql-session/lib/index.js:271:10)
    at Query.Sequence.end (/home/ubuntu/workspace/now/node_modules/mysql/lib/protocol/sequences/Sequence.js:88:24)
    at Query._handleFinalResultPacket (/home/ubuntu/workspace/now/node_modules/mysql/lib/protocol/sequences/Query.js:139:8)
    at Query.OkPacket (/home/ubuntu/workspace/now/node_modules/mysql/lib/protocol/sequences/Query.js:72:10)
    at Protocol._parsePacket (/home/ubuntu/workspace/now/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/home/ubuntu/workspace/now/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/home/ubuntu/workspace/now/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/home/ubuntu/workspace/now/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:96:13)
```

Please help, this is really annoying
Thanks!

**Comment by chill117** [comment]
The errors are caused by a missing callback function. Try this:
```js
Session.reload(function() {
    // reload done
});

Session.regenerate(function() {
    // regenerate done
});
```
The above is a short-term fix for your current situation.

A long-term fix to this module could be to make the callback optional for these session methods.

**Comment by sirhypernova** [comment]
Ok, thats all good, but sessions still don't stay after page refresh. It just detects every time that there is nothing, and to confirm they do go into the database.
Any ideas on that matter?

**Comment by sirhypernova** [comment]
Here you can see what I did to get the data:
app.get('/username', function(req, res) {
 ```
 // req.session.reload(function () {
     res.send(req.session.username);
    // console.log(req.session.username);
  // });
});
```
And setting them here:
```
app.post('/login', function(req, res) {
    var username = req.body.username;
    var password = req.body.password;
    var login = fs.readFileSync('auth.json');
    login = JSON.parse(login);
    var user = _.findKey(login.users,{'username':username});
    var user = login.users[user];
    if (!user) {
        res.send('failed');
        return;
    }
    var correct = bcrypt.compareSync(password,user.password);
    if (correct) {
        if (users.includes(username)) {
            res.send('already');
            return;
        }
        res.send('success');
        req.session.regenerate(function () {
          req.session.username = username;
          req.session.save();
        });
        return;
    } else {
        res.send('fail');
        return;
    }
});
```

**Comment by chill117** [comment]
Try this for your session config:
```js
app.use(session({
  secret: 'SECRET',
  store: sessionStore,
  resave: true,
  saveUninitialized: true,
  cookie: {
    maxAge: 60*60*60*24,
    httpOnly: false ,
    domain:'localhost:8080',
    path: '/',
    secure: false
  }
}));
```

And a couple notes:
* `httpOnly` should be `true` because it helps prevent session hijacking in cases of XSS vulnerabilities; the cookie isn't readable by JavaScript when HTTP-only.
* You should avoid using bcrypt synchronously because it makes your website/service vulnerable to denial of service attacks.
