### ISSUE TITLE
Syntax for creating customized session tables?

### ISSUE THREAD

**Issue by nickelow** [chill117/express-mysql-session#83]
Hello, I am trying to insert my session data into an existing sessions table with some custom fields, and it does not seem to work. Here is my code:

```js
const dbInfo = {
  host: 'localhost',
  port: 3306,
  user: 'root',
  password: null,
  database: 'workplace_hub',
  schema: {
    tableName: 'sessions',
    columnNames: {
      id: 'session_id',
      createdAt: 'expires',
      headers: 'headers',
      userId: 'userId',
    }
  }
};

const options = {
  checkExpirationInterval: 1000 * 60 * 15,
  expiration: 86400000,
  createDatabaseTable: true,
};

const connection = mysql.createConnection(dbInfo);
const sessionStore = new MySQLStore(options, connection);
module.exports = session({
  secret: 'nickelow',
  store: sessionStore,
  resave: false,
  saveUninitialized: false,
  cookie: {
    secure: false,
    httpOnly: false,
    maxAge: 86400000,
  },
});
```

The table is being created, but the fields are still 'session_id', 'expires', and 'data'.

**Comment by chill117** [comment]
Hello. It is only possible to set the table name and a few column names via this module's config:
```js
	schema: {
		tableName: 'custom_sessions_table_name',
		columnNames: {
			session_id: 'custom_session_id',
			expires: 'custom_expires_column_name',
			data: 'custom_data_column_name'
		}
	}
```
When you do this, it is necessary to create the database table yourself before initializing the MySQL session store.

**Comment by quiltykim** [comment]
I had also tried to make my own columns and followed the advice to create my own database table rather than relying on the module to do so with the same column naming.  The columns I've included are identical to the OP:

```
schema: {
    tableName: 'sessions',
    columnNames: {
      id: 'session_id',
      createdAt: 'expires',
      headers: 'headers',
      userId: 'userId',
    }
  }

```
The table in my mysql db also have these columns.

Unfortunately, I get this error:
```
Error: ER_BAD_FIELD_ERROR: Unknown column 'data' in 'field list'
    at Query.Sequence._packetToError (/home/user/code/session/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/home/user/code/session/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/home/user/code/session/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/home/user/code/session/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/home/user/code/session/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/home/qkay/code/user/code/session/node_modules/mysql/lib/Connection.js:103:28)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:280:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Socket.Readable.push (_stream_readable.js:220:10)
    at TCP.onread (net.js:638:20)
    --------------------
    at Pool.query (/home/user/code/session/node_modules/mysql/lib/Pool.js:199:23)
    at MySQLStore.query (/home/user/code/session/node_modules/express-mysql-session/index.js:388:33)
    at MySQLStore.get (/home/user/code/session/node_modules/express-mysql-session/index.js:137:8)
    at session (/home/user/code/session/node_modules/express-session/index.js:460:11)
    at Layer.handle [as handle_request] (/home/user/code/session/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/user/code/session/node_modules/express/lib/router/index.js:317:13)
    at /home/user/code/session/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/user/code/session/node_modules/express/lib/router/index.js:335:12)
    at next (/home/user/code/session/node_modules/express/lib/router/index.js:275:10)
    at parseCookies (/home/user/code/session/server/middleware/cookieParser.js:13:3)
    at Layer.handle [as handle_request] (/home/user/code/session/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/user/code/session/node_modules/express/lib/router/index.js:317:13)
    at /home/user/code/session/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/user/code/session/node_modules/express/lib/router/index.js:335:12)
    at next (/home/user/code/session/express/lib/router/index.js:275:10)
    at SendStream.error (/home/user/code/session/node_modules/serve-static/index.js:121:7)
```
Thanks again for this module!

**Comment by chill117** [comment]
The code that the OP used was incorrect because the keys they defined in their options object did not follow the documentation. The following is the correct way to define your custom column names:
```js
	schema: {
		tableName: 'custom_sessions_table_name',
		columnNames: {
			session_id: 'custom_session_id',
			expires: 'custom_expires_column_name',
			data: 'custom_data_column_name'
		}
	}
```

**Comment by chill117** [comment]
An error will now been thrown when using the `MySQLStore` constructor with unknown column(s) in the `schema` option. See commit [62228d1](https://github.com/chill117/express-mysql-session/commit/62228d17f19c079486672e078e9a2278a573c07e) for more info.
