### ISSUE TITLE
DeprecationWarning: timers.enroll() is deprecated

### ISSUE THREAD

**Issue by dragonfriend0013** [chill117/express-mysql-session#87]
Getting a deprecation warning in mysql version 2.15.* when running under node 10.8.0.  mysql version needs to be updated to mysql 2.16.* to correct depreciation warnings

(node:5423) [DEP0095] DeprecationWarning: timers.enroll() is deprecated. Please use setTimeout instead.
2018-08-06 12:11:30.922 SpecDesigner WARN Warning issued.  DeprecationWarning: timers.enroll() is deprecated. Please use setTimeout instead.:DeprecationWarning: timers.enroll() is deprecated. Please use setTimeout instead.
    at Protocol._startSequence (/Users/jamurphy/git/specdesigner/node_modules/express-mysql-session/node_modules/mysql/lib/protocol/Protocol.js:347:12)
    at Protocol._enqueue (/Users/jamurphy/git/specdesigner/node_modules/express-mysql-session/node_modules/mysql/lib/protocol/Protocol.js:190:10)
    at Protocol.handshake (/Users/jamurphy/git/specdesigner/node_modules/express-mysql-session/node_modules/mysql/lib/protocol/Protocol.js:52:23)
    at PoolConnection.connect (/Users/jamurphy/git/specdesigner/node_modules/express-mysql-session/node_modules/mysql/lib/Connection.js:130:18)
    at Pool.getConnection (/Users/jamurphy/git/specdesigner/node_modules/express-mysql-session/node_modules/mysql/lib/Pool.js:48:16)
    at Pool.query (/Users/jamurphy/git/specdesigner/node_modules/express-mysql-session/node_modules/mysql/lib/Pool.js:202:8)
    at MySQLStore.query (/Users/jamurphy/git/specdesigner/node_modules/express-mysql-session/index.js:388:33)
    at MySQLStore.<anonymous> (/Users/jamurphy/git/specdesigner/node_modules/express-mysql-session/index.js:110:9)
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
(node:5423) [DEP0096] DeprecationWarning: timers.unenroll() is deprecated. Please use clearTimeout instead.
2018-08-06 12:11:30.929 SpecDesigner WARN Warning issued.  DeprecationWarning: timers.unenroll() is deprecated. Please use clearTimeout instead.:DeprecationWarning: timers.unenroll() is deprecated. Please use clearTimeout instead.
    at Protocol._dequeue (/Users/jamurphy/git/specdesigner/node_modules/express-mysql-session/node_modules/mysql/lib/protocol/Protocol.js:325:10)
    at Handshake.<anonymous> (/Users/jamurphy/git/specdesigner/node_modules/express-mysql-session/node_modules/mysql/lib/protocol/Protocol.js:161:12)
    at Handshake.emit (events.js:182:13)
    at Handshake.Sequence.end (/Users/jamurphy/git/specdesigner/node_modules/express-mysql-session/node_modules/mysql/lib/protocol/sequences/Sequence.js:91:12)
    at Handshake.Sequence.OkPacket (/Users/jamurphy/git/specdesigner/node_modules/express-mysql-session/node_modules/mysql/lib/protocol/sequences/Sequence.js:97:8)
    at Protocol._parsePacket (/Users/jamurphy/git/specdesigner/node_modules/express-mysql-session/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/Users/jamurphy/git/specdesigner/node_modules/express-mysql-session/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/jamurphy/git/specdesigner/node_modules/express-mysql-session/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/jamurphy/git/specdesigner/node_modules/express-mysql-session/node_modules/mysql/lib/Connection.js:103:28)
    at Socket.emit (events.js:182:13)

**Comment by chill117** [comment]
Fixed and in new release
